import { serverTimestamp } from "firebase/firestore";
import { createCollectionApi } from "@/lib/db/base";
import type { EventDoc, WithId } from "@/types/collection";
import { eventDocumentSchema } from "@/features/event/schema";
import {
  buildOrganizationPathCandidates,
  eventBelongsToOrganization,
  sortEventsByUpdatedAt,
} from "@/features/event/utils";

const eventApi = createCollectionApi<EventDoc>("Event");

export { serverTimestamp };

// Standard CRUD helpers for the "Event" collection, generated by the shared
// collection API. `createEvent` is the one the create flow calls to write a new
// event document (see event-form-core.ts → submitEventForm, create branch).
export const {
  create: createEvent,
  set: setEvent,
  getById: getEventById,
  getAll: getEvents,
  update: updateEvent,
  remove: deleteEvent,
  findWhere: findEventsByField,
  findMany: findManyEvents,
} = eventApi;

function parseEvent<T extends EventDoc>(event: T) {
  const result = eventDocumentSchema.safeParse(event);
  return result.success ? result.data : null;
}

export async function getEventsForOrganization(organizationId: string) {
  const matches = await Promise.all(
    buildOrganizationPathCandidates(organizationId).map((path) =>
      findEventsByField("organizationPath", path),
    ),
  );

  const uniqueEvents = new Map<string, WithId<EventDoc>>();

  for (const group of matches) {
    for (const event of group) {
      const parsed = parseEvent(event);
      if (!parsed) continue;
      uniqueEvents.set(event.id, { ...event, ...parsed });
    }
  }

  return sortEventsByUpdatedAt(Array.from(uniqueEvents.values()));
}

export async function getEventForOrganization(
  eventId: string,
  organizationId: string,
) {
  const event = await getEventById(eventId);

  if (!event) {
    return null;
  }

  const parsed = parseEvent(event);

  if (!parsed || !eventBelongsToOrganization(parsed, organizationId)) {
    return null;
  }

  return {
    ...event,
    ...parsed,
  };
}
//factory pattern

// Example of the factory pattern. Not fully tested. Need to add pagination.

// Get Event
// const eventId = await eventApi.create(data);
// OR
// const eventId = await createEvent({
//     allowOverlap: false,
//     capacity: 50,
//     createdAt: serverTimestamp(),
//     updatedAt: serverTimestamp(),
//     description: "Annual Tech Meetup",
//     expectedGuests: 40,
//     formPath: "/forms/tech-meetup",
//     invoicePath: "/invoices/tech-meetup",
//     name: "Tech Meetup 2026",
//     organizationPath: "/organizations/dev-club",
//     periods: [
//         new Map([
//             ["start", "2026-05-01T10:00:00"],
//             ["end", "2026-05-01T12:00:00"],
//         ])
//     ],
//     status: "Draft",
//     timezone: "Asia/Singapore",
// });

// // Get Event by Id
// const event = await getEventById("abc123");

// // Get all Events
// const events = await getEvents();

// // Update Event
// await updateEvent("abc123", {
//     status: "Published",
//     updatedAt: serverTimestamp(),
// });

// // Query Event
// const publishedEvents = await findEventsByField("status", "Published");

// // Custom query using Firestore constraints
// import { where, orderBy, limit } from "firebase/firestore";
// import { findManyEvents } from "@/lib/db/event";

// const events = await findManyEvents(
//     where("status", "==", "Published"),
//     orderBy("createdAt", "desc"),
//     limit(5)
// );

// // Delete Event
// await deleteEvent("abc123");
